# Generated by Django 3.2.11 on 2022-01-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_identifier', models.CharField(default='changeme', max_length=4096)),
                ('raw_identifier', models.CharField(default='changeme', max_length=4096)),
                ('enrolled', models.DateTimeField()),
                ('last_fetched', models.DateTimeField()),
            ],
        ),
    ]
