# Generated by Django 3.2.11 on 2022-02-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_auto_20220119_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionruleset',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
