# pylint: skip-file
# Generated by Django 3.2.12 on 2022-05-12 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_extensionruleset_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.DateTimeField()),
                ('task', models.CharField(max_length=1024)),
                ('slug', models.SlugField(max_length=1024)),
                ('url', models.URLField(max_length=1024)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='enrollment.enrollment')),
            ],
        ),
    ]
