# pylint: skip-file
# Generated by Django 3.2.13 on 2022-06-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_scheduledtask_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_uninstalled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
