# pylint: skip-file
# Generated by Django 3.2.13 on 2022-06-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0006_enrollment_last_uninstalled'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='metadata',
            field=models.TextField(default='{}', max_length=16777216),
        ),
    ]
