# pylint: skip-file
# Generated by Django 3.2.13 on 2022-06-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0007_scheduledtask_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleMatchCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024)),
                ('pattern', models.CharField(max_length=1024)),
                ('matches', models.IntegerField()),
                ('checked', models.DateTimeField()),
            ],
        ),
    ]
