# pylint: skip-file
# Generated by Django 3.2.13 on 2022-07-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0008_rulematchcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='email_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
