# pylint: skip-file
# Generated by Django 3.2.13 on 2022-07-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0010_rename_email_after_enrollment_contact_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='metadata',
            field=models.TextField(default='{}', max_length=16777216),
        ),
    ]
