# pylint: skip-file
# Generated by Django 3.2.14 on 2022-07-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0011_enrollment_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulematchcount',
            name='content',
            field=models.TextField(blank=True, max_length=67108864, null=True),
        ),
    ]
