# pylint: skip-file
# Generated by Django 3.2.14 on 2022-08-10 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0012_rulematchcount_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024)),
                ('retrieved', models.DateTimeField()),
                ('content', models.TextField(blank=True, max_length=67108864, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rulematchcount',
            name='page_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrollment.pagecontent'),
        ),
    ]
