# pylint: skip-file
# Generated by Django 3.2.14 on 2022-08-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0013_auto_20220810_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulematchcount',
            name='content',
        ),
    ]
