# pylint: skip-file
# Generated by Django 3.2.15 on 2022-10-05 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0015_alter_rulematchcount_page_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='enrollment.enrollmentgroup'),
        ),
    ]
