# pylint: skip-file
# Generated by Django 3.2.17 on 2023-06-03 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0016_auto_20221004_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['assigned_identifier']},
        ),
        migrations.AlterModelOptions(
            name='enrollmentgroup',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='extensionruleset',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='assigned_identifier',
            field=models.CharField(default='changeme', max_length=4096, verbose_name='Identifier'),
        ),
        migrations.CreateModel(
            name='ArchivedExtensionRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_json', models.TextField(default='[]', max_length=16777216)),
                ('active_until', models.DateTimeField()),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_versions', to='enrollment.extensionruleset')),
            ],
            options={
                'ordering': ['rule_set'],
            },
        ),
    ]
