# pylint: skip-file
# Generated by Django 3.2.17 on 2023-06-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0017_auto_20230602_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedextensionruleset',
            options={'ordering': ['-active_until']},
        ),
    ]
