# pylint: skip-file
# Generated by Django 3.2.17 on 2023-08-02 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0018_alter_archivedextensionruleset_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_url', models.URLField(blank=True, null=True)),
                ('item_type', models.CharField(blank=True, max_length=4096, null=True)),
                ('item_name', models.CharField(blank=True, max_length=4096, null=True)),
                ('item_url', models.CharField(blank=True, max_length=4096, null=True)),
                ('item_price', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=1048576, null=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='enrollment.enrollmentgroup')),
            ],
        ),
        migrations.CreateModel(
            name='AmazonPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_url', models.URLField(blank=True, max_length=4096, null=True)),
                ('item_type', models.CharField(blank=True, max_length=4096, null=True)),
                ('item_name', models.CharField(blank=True, max_length=4096, null=True)),
                ('item_url', models.CharField(blank=True, max_length=4096, null=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='enrollment.enrollmentgroup')),
            ],
        ),
    ]
