# pylint: skip-file
# Generated by Django 3.2.17 on 2023-08-02 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0019_amazonpurchase_amazonreward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonpurchase',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='enrollment.enrollment'),
        ),
        migrations.AlterField(
            model_name='amazonreward',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='enrollment.enrollment'),
        ),
    ]
