# pylint: skip-file
# Generated by Django 3.2.20 on 2023-08-05 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('enrollment', '0020_auto_20230802_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazonpurchase',
            old_name='participant',
            new_name='enrollment',
        ),
        migrations.RenameField(
            model_name='amazonpurchase',
            old_name='wishlist_url',
            new_name='order_url',
        ),
        migrations.AddField(
            model_name='amazonpurchase',
            name='purchase_date',
            field=models.DateField(default=datetime.date(2023, 8, 5)),
            preserve_default=False,
        ),
    ]
